### ISSUE TITLE
mysql_pubkey.asc is moved to files from files/default without updating attribute file

### ISSUE THREAD

**Issue by sosomagic** [sous-chefs/yum-mysql-community#14]
This is done by this commit:
https://github.com/chef-cookbooks/yum-mysql-community/commit/b119dedcb8b487aa5c0fa9fcb760b5e48e7041d0#diff-a8e27ca6e9ac5ee1e9258effd3c1dd90

**Comment by sosomagic** [comment]
This causes failure when install mysql from this cookbook.

**Comment by tas50** [comment]
@sosomagic Can you show me exactly what attribute is failing due to this move. I can't see how this could be causing failures unless you're on Chef 11.

**Comment by sosomagic** [comment]
@tas50 In attributes/mysql57-community.rb, you were using 
"-default['yum']['mysql57-community']['gpgkey'] = 'https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/default/mysql_pubkey.asc'"

If people are using an older version of your cookbook, they have this gpgkey added in the yum repo file. So when chef install mysql, it will try to get the key from this url, which actually has been moved.

Even if you guys updated the gpgkey now, it still breaks the backward compatibility.
